# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout

      - run:
          name: "Install dependencies"
          command: npm install

      - run:
          name: "Run UI tests"
          command: npx playwright test

      - run:
          name: "Run API test 1"
          command: npx jest case3.js

      - run:
          name: "Run API test 2"
          command: npx jest case4.js

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          - store_test_results:
              path: ~/test-results
          - store_artifacts:
              path: ~/test-results/junit


          #             # Start local server
          #             npm run start &
          #             npx wait-on http://localhost:3000
          #             replace below with command you want to run, example for running a script below


          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node